//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdSrv3.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupChild
    {
        public int Key { get; set; }
        public int ParentKey { get; set; }
        public System.Guid ChildGroupID { get; set; }
    
        public virtual Group Group { get; set; }
    }
}
