//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdSrv3.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IdentityServerEntities : DbContext
    {
        public IdentityServerEntities()
            : base("name=IdentityServerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<ClientClaim> ClientClaims { get; set; }
        public virtual DbSet<ClientCorsOrigin> ClientCorsOrigins { get; set; }
        public virtual DbSet<ClientCustomGrantType> ClientCustomGrantTypes { get; set; }
        public virtual DbSet<ClientIdPRestriction> ClientIdPRestrictions { get; set; }
        public virtual DbSet<ClientPostLogoutRedirectUri> ClientPostLogoutRedirectUris { get; set; }
        public virtual DbSet<ClientRedirectUri> ClientRedirectUris { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<ClientScope> ClientScopes { get; set; }
        public virtual DbSet<ClientSecret> ClientSecrets { get; set; }
        public virtual DbSet<Consent> Consents { get; set; }
        public virtual DbSet<GroupChild> GroupChilds { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<LinkedAccountClaim> LinkedAccountClaims { get; set; }
        public virtual DbSet<LinkedAccount> LinkedAccounts { get; set; }
        public virtual DbSet<PasswordResetSecret> PasswordResetSecrets { get; set; }
        public virtual DbSet<ScopeClaim> ScopeClaims { get; set; }
        public virtual DbSet<Scope> Scopes { get; set; }
        public virtual DbSet<ScopeSecret> ScopeSecrets { get; set; }
        public virtual DbSet<Token> Tokens { get; set; }
        public virtual DbSet<TwoFactorAuthToken> TwoFactorAuthTokens { get; set; }
        public virtual DbSet<UserAccount> UserAccounts { get; set; }
        public virtual DbSet<UserCertificate> UserCertificates { get; set; }
        public virtual DbSet<UserClaim> UserClaims { get; set; }
    }
}
