//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdSrv3.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAccount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserAccount()
        {
            this.LinkedAccountClaims = new HashSet<LinkedAccountClaim>();
            this.LinkedAccounts = new HashSet<LinkedAccount>();
            this.PasswordResetSecrets = new HashSet<PasswordResetSecret>();
            this.TwoFactorAuthTokens = new HashSet<TwoFactorAuthToken>();
            this.UserCertificates = new HashSet<UserCertificate>();
            this.UserClaims = new HashSet<UserClaim>();
        }
    
        public int Key { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> Age { get; set; }
        public System.Guid ID { get; set; }
        public string Tenant { get; set; }
        public string Username { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public bool IsAccountClosed { get; set; }
        public Nullable<System.DateTime> AccountClosed { get; set; }
        public bool IsLoginAllowed { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public Nullable<System.DateTime> LastFailedLogin { get; set; }
        public int FailedLoginCount { get; set; }
        public Nullable<System.DateTime> PasswordChanged { get; set; }
        public bool RequiresPasswordReset { get; set; }
        public string Email { get; set; }
        public bool IsAccountVerified { get; set; }
        public Nullable<System.DateTime> LastFailedPasswordReset { get; set; }
        public int FailedPasswordResetCount { get; set; }
        public string MobileCode { get; set; }
        public Nullable<System.DateTime> MobileCodeSent { get; set; }
        public string MobilePhoneNumber { get; set; }
        public Nullable<System.DateTime> MobilePhoneNumberChanged { get; set; }
        public int AccountTwoFactorAuthMode { get; set; }
        public int CurrentTwoFactorAuthStatus { get; set; }
        public string VerificationKey { get; set; }
        public Nullable<int> VerificationPurpose { get; set; }
        public Nullable<System.DateTime> VerificationKeySent { get; set; }
        public string VerificationStorage { get; set; }
        public string HashedPassword { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LinkedAccountClaim> LinkedAccountClaims { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LinkedAccount> LinkedAccounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PasswordResetSecret> PasswordResetSecrets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TwoFactorAuthToken> TwoFactorAuthTokens { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserCertificate> UserCertificates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserClaim> UserClaims { get; set; }
    }
}
