//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdSrv3DataMigrationTool.EntityFrameworkModels.IdSrv3Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consent
    {
        public string Subject { get; set; }
        public string ClientId { get; set; }
        public string Scopes { get; set; }
    }
}
